"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
var AgoraUIKit_1 = require("./AgoraUIKit");
__createBinding(exports, AgoraUIKit_1, "default", "default");
var RtcConfigure_1 = require("./RtcConfigure");
__createBinding(exports, RtcConfigure_1, "default", "RtcConfigure");
var MaxVideoView_1 = require("./Views/MaxVideoView");
__createBinding(exports, MaxVideoView_1, "default", "MaxVideoView");
var MinVideoView_1 = require("./Views/MinVideoView");
__createBinding(exports, MinVideoView_1, "default", "MinVideoView");
var LocalUserContext_1 = require("./Contexts/LocalUserContext");
__createBinding(exports, LocalUserContext_1, "default", "LocalUserContext");
__createBinding(exports, LocalUserContext_1, "LocalConsumer");
__createBinding(exports, LocalUserContext_1, "LocalProvider");
__createBinding(exports, LocalUserContext_1, "LocalContext");
var MaxUidContext_1 = require("./Contexts/MaxUidContext");
__createBinding(exports, MaxUidContext_1, "default", "MaxUidContext");
__createBinding(exports, MaxUidContext_1, "MaxUidConsumer");
__createBinding(exports, MaxUidContext_1, "MaxUidProvider");
var MinUidContext_1 = require("./Contexts/MinUidContext");
__createBinding(exports, MinUidContext_1, "default", "MinUidContext");
__createBinding(exports, MinUidContext_1, "MinUidConsumer");
__createBinding(exports, MinUidContext_1, "MinUidProvider");
var PropsContext_1 = require("./Contexts/PropsContext");
__createBinding(exports, PropsContext_1, "default", "PropsContext");
__createBinding(exports, PropsContext_1, "PropsConsumer");
__createBinding(exports, PropsContext_1, "PropsProvider");
var PropsContext_2 = require("./Contexts/PropsContext");
__createBinding(exports, PropsContext_2, "DualStreamMode");
var PropsContext_3 = require("./Contexts/PropsContext");
__createBinding(exports, PropsContext_3, "ClientRole");
__createBinding(exports, PropsContext_3, "ChannelProfile");
var RtcContext_1 = require("./Contexts/RtcContext");
__createBinding(exports, RtcContext_1, "default", "RtcContext");
__createBinding(exports, RtcContext_1, "RtcConsumer");
__createBinding(exports, RtcContext_1, "RtcProvider");
var BtnTemplate_1 = require("./Controls/BtnTemplate");
__createBinding(exports, BtnTemplate_1, "default", "BtnTemplate");
var EndCall_1 = require("./Controls/Local/EndCall");
__createBinding(exports, EndCall_1, "default", "Endcall");
var FullScreen_1 = require("./Controls/Local/FullScreen");
__createBinding(exports, FullScreen_1, "default", "FullScreen");
var LocalAudioMute_1 = require("./Controls/Local/LocalAudioMute");
__createBinding(exports, LocalAudioMute_1, "default", "LocalAudioMute");
var LocalVideoMute_1 = require("./Controls/Local/LocalVideoMute");
__createBinding(exports, LocalVideoMute_1, "default", "LocalVideoMute");
var SwitchCamera_1 = require("./Controls/Local/SwitchCamera");
__createBinding(exports, SwitchCamera_1, "default", "SwitchCamera");
var LocalControls_1 = require("./Controls/LocalControls");
__createBinding(exports, LocalControls_1, "default", "Controls");
var RemoteAudioMute_1 = require("./Controls/Remote/RemoteAudioMute");
__createBinding(exports, RemoteAudioMute_1, "default", "RemoteAudioMute");
var RemoteSwap_1 = require("./Controls/Remote/RemoteSwap");
__createBinding(exports, RemoteSwap_1, "default", "RemoteSwap");
var RemoteVideoMute_1 = require("./Controls/Remote/RemoteVideoMute");
__createBinding(exports, RemoteVideoMute_1, "default", "RemoteVideoMute");
var RemoteControls_1 = require("./Controls/RemoteControls");
__createBinding(exports, RemoteControls_1, "default", "RemoteControls");
var ImageIcon_1 = require("./Controls/ImageIcon");
__createBinding(exports, ImageIcon_1, "default", "ImageIcon");
